version: '{build}'
cache: c:\tools\vcpkg\installed\
platform:
  - x86
  - x64
configuration:
  - Debug
  - Profiling
  - Release
clone_folder: C:\NEWorld
clone_depth: 1
install:
  - if %PLATFORM% equ x86 (vcpkg.exe install sdl2 sdl2-image glew rpclib freetype) else (vcpkg.exe install sdl2:x64-windows sdl2-image:x64-windows glew:x64-windows rpclib:x64-windows freetype:x64-windows) > nul
build:
  project: build/VisualStudio_v15/NEWorld.sln
  verbosity: minimal
