version: '{build}'
cache: c:\tools\vcpkg\installed\
platform:
  - x86
  - x64
configuration:
  - Debug
  - Profiling
  - Release
clone_folder: C:\NEWorld
clone_depth: 1
install:
  - vcpkg.exe install sdl2 sdl2-image glew rpclib freetype
build:
  project: build/VisualStudio_v15/NEWorld.sln
  verbosity: minimal
